apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: counter-app
  labels:
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: counter-app
spec:
  source:
    git:
      url: https://github.com/carlosonunez-vmw/example-go-app
      ref:
        branch: main
